import type { MonthRecord } from "./types";

/**
 * Source: REAL_Manx_Growth_Solutions_Cashflow (Sheet1), read Aug 2026.
 *
 * Revenue, Profit and Closing/MGS Balance are taken verbatim from the
 * sheet's own totals row for each month wherever the sheet states them
 * (this is the ground truth the calculation engine is checked against).
 * Per-client and per-expense line items were reconstructed by solving
 * them against those totals (the sheet's column alignment was lossy in
 * the PDF export) - every month below reconciles exactly to the sheet's
 * stated Revenue figure. Months with no stated Profit/Balance are pure
 * forecast and get computed live by the calc engine.
 *
 * Anything wrong here can be fixed in the in-app Data Editor - it's not
 * necessary to edit this file by hand.
 */
export const MONTHS: MonthRecord[] = [
  // ---------------- Self-employed period ----------------
  {
    key: "2024-10",
    label: "Oct 2024",
    phase: "self-employed",
    forecast: false,
    clients: [],
    subscriptions: 56.16,
    brandExpense: 0,
    subcontractExpense: 200,
    knownRevenue: 0,
    knownProfit: -256.16,
    knownClosingBalance: -256.16,
  },
  {
    key: "2024-11",
    label: "Nov 2024",
    phase: "self-employed",
    forecast: false,
    clients: [{ name: "Client 1", amount: 400 }],
    subscriptions: 67.23,
    brandExpense: 0,
    subcontractExpense: 200,
    knownRevenue: 400,
    knownProfit: 132.77,
    knownClosingBalance: -123.39,
  },
  {
    key: "2024-12",
    label: "Dec 2024",
    phase: "self-employed",
    forecast: false,
    clients: [{ name: "Client 1", amount: 400 }],
    subscriptions: 86.01,
    brandExpense: 0,
    subcontractExpense: 300,
    knownRevenue: 400,
    knownProfit: 13.99,
    knownClosingBalance: -109.4,
  },
  {
    key: "2025-01",
    label: "Jan 2025",
    phase: "self-employed",
    forecast: false,
    clients: [{ name: "Client 1", amount: 600 }],
    subscriptions: 114.92,
    brandExpense: 0,
    subcontractExpense: 500,
    knownRevenue: 600,
    knownProfit: -14.92,
    knownClosingBalance: -124.32,
  },
  {
    key: "2025-02",
    label: "Feb 2025",
    phase: "self-employed",
    forecast: false,
    clients: [{ name: "Client 1", amount: 850 }],
    subscriptions: 72.31,
    brandExpense: 0,
    subcontractExpense: 625,
    knownRevenue: 850,
    knownProfit: 152.69,
    knownClosingBalance: 28.37,
  },
  {
    key: "2025-03",
    label: "Mar 2025",
    phase: "self-employed",
    forecast: false,
    clients: [
      { name: "Client 1", amount: 600 },
      { name: "Client 2", amount: 350 },
    ],
    subscriptions: 92.31,
    brandExpense: 0,
    subcontractExpense: 600,
    knownRevenue: 950,
    knownProfit: 257.69,
    knownClosingBalance: 286.06,
  },
  {
    key: "2025-04",
    label: "Apr 2025",
    phase: "self-employed",
    forecast: false,
    clients: [
      { name: "Client 1", amount: 600 },
      { name: "Client 2", amount: 350 },
    ],
    subscriptions: 92.31,
    brandExpense: 0,
    subcontractExpense: 500,
    knownRevenue: 950,
    knownProfit: 357.69,
    knownClosingBalance: 643.75,
  },
  {
    key: "2025-05",
    label: "May 2025",
    phase: "self-employed",
    forecast: false,
    clients: [
      { name: "Client 1", amount: 600 },
      { name: "Client 2", amount: 105 },
    ],
    subscriptions: 92.31,
    brandExpense: 0,
    subcontractExpense: 600,
    knownRevenue: 705,
    knownProfit: 12.69,
    knownClosingBalance: 656.44,
  },
  {
    key: "2025-06",
    label: "Jun 2025",
    phase: "self-employed",
    forecast: false,
    clients: [
      { name: "Client 1", amount: 800 },
      { name: "Client 3", amount: 125 },
    ],
    subscriptions: 182.44,
    brandExpense: 700, // ReBrand
    subcontractExpense: 1500,
    knownRevenue: 925,
    knownProfit: -1457.44,
    knownClosingBalance: -801,
  },
  {
    key: "2025-07",
    label: "Jul 2025",
    phase: "self-employed",
    forecast: false,
    clients: [
      { name: "Client 1", amount: 800 },
      { name: "Client 3", amount: 250 },
      { name: "Client 4", amount: 1000 },
    ],
    subscriptions: 81.81,
    brandExpense: 250, // Accountant fee
    subcontractExpense: 1000,
    knownRevenue: 2050,
    knownProfit: 718.19,
    knownClosingBalance: -82.81,
  },

  // ---------------- Limited company period ----------------
  {
    key: "2025-08",
    label: "Aug 2025",
    phase: "limited-company",
    forecast: false,
    clients: [
      { name: "Client 1", amount: 1100 },
      { name: "Client 3", amount: 125 },
      { name: "Sanctuary Trust", amount: 1000 },
    ],
    subscriptions: 81.81,
    brandExpense: 750,
    subcontractExpense: 1695,
    knownRevenue: 2225,
    knownProfit: -301.81,
    knownClosingBalance: 196.38,
  },
  {
    key: "2025-09",
    label: "Sep 2025",
    phase: "limited-company",
    forecast: false,
    clients: [
      { name: "Client 1", amount: 580 },
      { name: "Sanctuary Trust", amount: 1000 },
    ],
    subscriptions: 580,
    brandExpense: 0,
    subcontractExpense: 1000,
    knownRevenue: 1580,
    knownProfit: 498.19,
    knownClosingBalance: 118.57,
  },
  {
    key: "2025-10",
    label: "Oct 2025",
    phase: "limited-company",
    forecast: false,
    clients: [
      { name: "Client 1", amount: 900 },
      { name: "Sanctuary Trust", amount: 1000 },
    ],
    subscriptions: 81.81,
    brandExpense: 256,
    subcontractExpense: 1640,
    knownRevenue: 1900,
    knownProfit: -77.81,
    knownClosingBalance: 1237.47,
  },
  {
    key: "2025-11",
    label: "Nov 2025",
    phase: "limited-company",
    forecast: false,
    clients: [
      { name: "Client 1", amount: 450 },
      { name: "Sanctuary Trust", amount: 1000 },
      { name: "PGI", amount: 250 },
    ],
    subscriptions: 81.1,
    brandExpense: 750,
    subcontractExpense: 1200,
    knownRevenue: 1700,
    knownProfit: 1118.9,
    knownClosingBalance: 355.66,
  },
  {
    key: "2025-12",
    label: "Dec 2025",
    phase: "limited-company",
    forecast: false,
    clients: [
      { name: "Sanctuary Trust", amount: 1000 },
      { name: "PGI", amount: 650 },
    ],
    subscriptions: 81.81,
    brandExpense: 0,
    subcontractExpense: 1700,
    knownRevenue: 1650,
    knownProfit: -881.81,
    knownClosingBalance: 302.85,
    notes: "Client 1 churned (dropped to £0/mo per source sheet).",
  },
  {
    key: "2026-01",
    label: "Jan 2026",
    phase: "limited-company",
    forecast: false,
    clients: [
      { name: "Sanctuary Trust", amount: 1000 },
      { name: "PGI", amount: 650 },
    ],
    subscriptions: 197.81,
    brandExpense: 625,
    subcontractExpense: 1505,
    knownRevenue: 1650,
    knownProfit: -52.81,
    knownClosingBalance: 250.04,
  },
  {
    key: "2026-02",
    label: "Feb 2026",
    phase: "limited-company",
    forecast: false,
    clients: [
      { name: "Sanctuary Trust", amount: 1000 },
      { name: "PGI", amount: 650 },
      { name: "Whittles", amount: 1300 },
    ],
    subscriptions: 197.81,
    brandExpense: 0,
    subcontractExpense: 1660,
    knownRevenue: 2950,
    knownProfit: 665,
    knownClosingBalance: 915.04,
  },
  {
    key: "2026-03",
    label: "Mar 2026",
    phase: "limited-company",
    forecast: false,
    clients: [
      { name: "Sanctuary Trust", amount: 1000 },
      { name: "PGI", amount: 650 },
      { name: "Whittles", amount: 1300 },
    ],
    subscriptions: 197.81,
    brandExpense: 150,
    subcontractExpense: 1670,
    knownRevenue: 2950,
    knownProfit: 1082.19,
    knownClosingBalance: 1997.23,
  },
  {
    key: "2026-04",
    label: "Apr 2026",
    phase: "limited-company",
    forecast: false,
    clients: [
      { name: "Sanctuary Trust", amount: 1000 },
      { name: "PGI", amount: 650 },
      { name: "Whittles", amount: 1300 },
      { name: "Group Eleven", amount: 1000 },
    ],
    subscriptions: 214.81,
    brandExpense: 840,
    subcontractExpense: 1835,
    knownRevenue: 3950,
    knownProfit: 1750.19,
    knownClosingBalance: 3747.42,
  },
  {
    key: "2026-05",
    label: "May 2026",
    phase: "limited-company",
    forecast: false,
    clients: [
      { name: "Sanctuary Trust", amount: 1000 },
      { name: "PGI", amount: 800 },
      { name: "Whittles", amount: 1300 },
      { name: "Group Eleven", amount: 1000 },
    ],
    subscriptions: 259.81,
    brandExpense: 0,
    subcontractExpense: 2200,
    knownRevenue: 4100,
    knownProfit: 800.19,
    knownClosingBalance: 4547.61,
  },
  {
    key: "2026-06",
    label: "Jun 2026",
    phase: "limited-company",
    forecast: false,
    clients: [
      { name: "Sanctuary Trust", amount: 1000 },
      { name: "PGI", amount: 800 },
      { name: "Whittles", amount: 1300 },
      { name: "Group Eleven", amount: 1000 },
    ],
    subscriptions: 259.81,
    brandExpense: 0,
    subcontractExpense: 2545,
    knownRevenue: 4100,
    knownProfit: 1295.19,
    knownClosingBalance: 5842.8,
  },
  {
    key: "2026-07",
    label: "Jul 2026",
    phase: "limited-company",
    forecast: false,
    clients: [
      { name: "Sanctuary Trust", amount: 1000 },
      { name: "PGI", amount: 800 },
      { name: "Whittles", amount: 1300 },
      { name: "Group Eleven", amount: 1000 },
    ],
    subscriptions: 293.81,
    brandExpense: 0,
    subcontractExpense: 2300,
    knownRevenue: 4100,
    knownProfit: 1506.19,
    knownClosingBalance: 6425.19,
  },
  {
    key: "2026-08",
    label: "Aug 2026",
    phase: "limited-company",
    forecast: false,
    clients: [
      { name: "Sanctuary Trust", amount: 1000 },
      { name: "PGI", amount: 800 },
      { name: "Whittles", amount: 1300 },
      { name: "Group Eleven", amount: 1000 },
      { name: "PDMS", amount: 1166 },
    ],
    subscriptions: 340.81,
    brandExpense: 0,
    subcontractExpense: 2500,
    knownRevenue: 5266,
    knownProfit: 2425.19,
    knownClosingBalance: 6234.38,
    notes: "Current month.",
  },
  {
    key: "2026-09",
    label: "Sep 2026",
    phase: "limited-company",
    forecast: false,
    clients: [
      { name: "Sanctuary Trust", amount: 1000 },
      { name: "PGI", amount: 800 },
      { name: "Whittles", amount: 1300 },
      { name: "Group Eleven", amount: 1000 },
      { name: "PDMS", amount: 1166 },
      { name: "Aston", amount: 1300 },
    ],
    subscriptions: 340.81,
    brandExpense: 0,
    subcontractExpense: 6416, // one-off spike per source sheet (incl. MM/NI/wages)
    knownRevenue: 6566,
    knownProfit: -190.81,
    // no stated closing balance for this month in the source - computed instead
  },
  // ---- Beyond this point the source sheet has no stated Profit/Balance;
  //      everything below is forecast and computed live by the calc engine.
  //      "Predicted client" lines are the orange rows from the source sheet. ----
  {
    key: "2026-10",
    label: "Oct 2026",
    phase: "limited-company",
    forecast: true,
    clients: [
      { name: "Sanctuary Trust", amount: 1000 },
      { name: "PGI", amount: 800 },
      { name: "Whittles", amount: 1300 },
      { name: "Group Eleven", amount: 1000 },
      { name: "PDMS", amount: 1166 },
      { name: "Aston", amount: 1300 },
      { name: "Predicted client 10", amount: 900, predicted: true },
    ],
    subscriptions: 340.81,
    brandExpense: 0,
    subcontractExpense: 2500,
    knownRevenue: 7466,
  },
  {
    key: "2026-11",
    label: "Nov 2026",
    phase: "limited-company",
    forecast: true,
    clients: [
      { name: "Sanctuary Trust", amount: 1000 },
      { name: "PGI", amount: 800 },
      { name: "Whittles", amount: 1300 },
      { name: "Group Eleven", amount: 1000 },
      { name: "PDMS", amount: 1166 },
      { name: "Aston", amount: 1300 },
      { name: "Predicted client 10", amount: 900, predicted: true },
      { name: "Predicted client 13", amount: 900, predicted: true },
    ],
    subscriptions: 340.81,
    brandExpense: 0,
    subcontractExpense: 2500,
    knownRevenue: 8366,
  },
  {
    key: "2026-12",
    label: "Dec 2026",
    phase: "limited-company",
    forecast: true,
    clients: [
      { name: "Sanctuary Trust", amount: 1000 },
      { name: "PGI", amount: 800 },
      { name: "Whittles", amount: 1300 },
      { name: "Group Eleven", amount: 1000 },
      { name: "PDMS", amount: 1166 },
      { name: "Aston", amount: 1300 },
      { name: "Predicted client 10", amount: 900, predicted: true },
      { name: "Predicted client 13", amount: 900, predicted: true },
      { name: "Predicted client 14", amount: 900, predicted: true },
    ],
    subscriptions: 340.81,
    brandExpense: 0,
    subcontractExpense: 2500,
    knownRevenue: 9266,
  },
  {
    key: "2027-01",
    label: "Jan 2027",
    phase: "limited-company",
    forecast: true,
    clients: [
      { name: "Sanctuary Trust", amount: 1000 },
      { name: "PGI", amount: 800 },
      { name: "Whittles", amount: 1300 },
      { name: "Group Eleven", amount: 1000 },
      { name: "PDMS", amount: 1166 },
      { name: "Aston", amount: 1300 },
      { name: "Predicted client 10", amount: 900, predicted: true },
      { name: "Predicted client 13", amount: 900, predicted: true },
      { name: "Predicted client 14", amount: 900, predicted: true },
      { name: "Predicted client 15", amount: 900, predicted: true },
    ],
    subscriptions: 340.81,
    brandExpense: 0,
    subcontractExpense: 2500,
    knownRevenue: 10166,
    notes:
      "Source sheet's header reads 'January 2026' here - almost certainly a typo for Jan 2027, corrected in this model.",
  },
  {
    key: "2027-02",
    label: "Feb 2027",
    phase: "limited-company",
    forecast: true,
    clients: [
      { name: "Sanctuary Trust", amount: 1000 },
      { name: "PGI", amount: 800 },
      { name: "Whittles", amount: 1300 },
      { name: "Group Eleven", amount: 1000 },
      { name: "PDMS", amount: 1166 },
      { name: "Aston", amount: 1300 },
      { name: "Predicted client 10", amount: 900, predicted: true },
      { name: "Predicted client 13", amount: 900, predicted: true },
      { name: "Predicted client 14", amount: 900, predicted: true },
      { name: "Predicted client 15", amount: 900, predicted: true },
    ],
    subscriptions: 340.81,
    brandExpense: 0,
    subcontractExpense: 2500,
    knownRevenue: 10166,
    notes:
      "Source sheet's header reads 'February 2026' here - almost certainly a typo for Feb 2027, corrected in this model. Predicted clients 16 & 17 appear on the source sheet but aren't reflected in this revenue figure yet - treat them as further upside, addable via the scenario simulator.",
  },
];

export const STARTING_BALANCE = 0; // MGS Balance before Oct 2024 (sheet starts at £0)
